version: '2.1'

services:
  php:
    build: .
    image: wuhu:latest
    volumes: &app_volumes
      - ./wuhu/www_admin:/var/www/www_admin
      - ./wuhu/www_party:/var/www/www_party
      - ./entries_private:/var/www/entries_private
      - ./entries_public:/var/www/entries_public
      - ./screenshots:/var/www/screenshots
      - mysqld-run:/run/mysqld
    restart: unless-stopped
    networks:
      - wuhu-shared-network

  admin:
    image: webdevops/apache:latest
    environment:
      WEB_DOCUMENT_ROOT: /var/www/www_admin
      WEB_ALIAS_DOMAIN: www.admin
      WEB_PHP_SOCKET: php:9000
    ports:
      - "8081:80"
    links:
      - php
    volumes: *app_volumes
    restart: unless-stopped
    networks:
      - wuhu-shared-network

  party:
    image: webdevops/apache:latest
    environment:
      WEB_DOCUMENT_ROOT: /var/www/www_party
      WEB_ALIAS_DOMAIN: www.party
      WEB_PHP_SOCKET: php:9000
    ports:
      - "8080:80"
    links:
      - php
    volumes: *app_volumes
    restart: unless-stopped
    networks:
      - wuhu-shared-network

  mysql:
    image: mariadb:latest
    ports:
      - "127.0.0.1:59824:3306"
    volumes:
      - ./database:/var/lib/mysql
      - mysqld-run:/run/mysqld
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: wuhu
      MYSQL_USER: wuhu
      MYSQL_PASSWORD: wuhu
    restart: unless-stopped
    networks:
      - wuhu-shared-network

volumes:
  mysqld-run:
    driver: "local"

networks:
  wuhu-shared-network:
    driver: bridge
